# Generated by Django 4.2.11 on 2024-03-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_color_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.IntegerField(),
        ),
    ]
